FROM python:3.13-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir --disable-pip-version-check -r requirements.txt
COPY redis-rest-server.py .

ENV PYTHONUNBUFFERED=1
EXPOSE 8080
CMD ["python", "redis-rest-server.py"]
