name: Nix Checks

on:
  push:
    branches: ["main", "NixOS", "full", "lite"]
  pull_request:
    branches: ["main", "full", "lite"]

permissions:
  contents: read

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Show flake outputs
        run: nix flake show --all-systems

      - name: Evaluate NixOS configuration
        run: |
          nix eval .#nixosConfigurations.gateway.config.system.build.toplevel.drvPath
